### ISSUE TITLE
npm support

### ISSUE THREAD

**Issue by gaydenko** [muicss/loadjs#6]
Hi!

I guess, it would be handy to publish the loader on npmjs.com to make it friendly for, say, browserify users.

**Comment by amorey** [comment]
@gaydenko Thanks for the suggestion. I thought about adding LoadJS to NPM but decided against it because:

1. LoadJS is meant to be inlined in the HTML so you can start using it without fetching a separate file
2. NPM/Browserify users have more sophisticated script loading capabilities at their disposal

Maybe I'm not thinking about it the right way though. I'd be curious to hear your thoughts on the LoadJS/NPM issue.

**Comment by gaydenko** [comment]
At the moment I use script.js bundled into SPA to load external service script (the last one can depend on user-agent and/or geolocation and can not be included into SPA bundle). That is by "loading" I mean something remote :)

**Comment by gaydenko** [comment]
On the other hand such tiny library can be easy included directly into an app, so closing the issue.
