### ISSUE TITLE
success doesn't fire when before returns false

### ISSUE THREAD

**Issue by wgehner** [muicss/loadjs#65]
I am trying a custom dom insert as below. The  'done'/success for 'form' never fires. Please advise.

			loadjs([
				'/assets/js/jquery.jsForm.min.js'
			], 'form', {
				async: false,
				success: function(){console.log('*form success*') /* doesn't fire */}, 
				error: function(pathsNotFound) {console.log('form error'+pathsNotFound)},
				before: function(path, scriptEl) {
					$('#content-wrapper').append(scriptEl)
					console.log('*before*') /* works */
					return false;
				}
			})
		loadjs.ready('form', function(){
			console.log('*form done*') /* doesn't fire */
		})

**Comment by amorey** [comment]
I think the issue is with `$('#content-wrapper').append(scriptEl)`. I'm not sure exactly what jQuery is doing under the hood but given that the `.append()` is operating on a collection maybe jQuery is copying `scriptEl` and replacing it with a new element. Performing the operation on the raw javascript object works:

```javascript
$('#content-wrapper')[0].append(scriptEl);
```
https://jsfiddle.net/muicss/mpnt5jx4/

**Comment by wgehner** [comment]
Works like a charm, thanks!
