### ISSUE TITLE
loadjs reports *false* error loading css on Edge 18

### ISSUE THREAD

**Issue by moos** [muicss/loadjs#81]
Loading a css file in Edge 18 (rel. Nov. 13, 2018) is causing a security error:

![screen shot 2018-12-06 at 10 39 15 am](https://user-images.githubusercontent.com/233047/49628879-8caa0580-f99b-11e8-9334-01980a4de2cf.png)

This is occurring on the line `if (!e.sheet.cssText.length) result = 'e';` and is masked by the try/catch.    However, the resource is loaded correctly.

Bin: https://jsbin.com/zuvaset/edit?html,console
PS: Edge 18 is available to try for free (1/2 hr. at a time!) on browserstack.

**Comment by amorey** [comment]
Thanks for creating an example page! I think the issue is that the CSS file is a cross-domain file so when the code tries to access `cssText` it gets a `SecurityError`. This PR should fix the problem:
https://github.com/muicss/loadjs/pull/82/files#diff-ef6e4b9de64d186abdf1a510bed822aaR141

I tested the code on IE Edge 18 and it seems to be working. Can you try out this version to see if you notice any problems?
https://cdn.rawgit.com/muicss/loadjs/crossdomaincss-bugfix/examples/assets/loadjs/loadjs.js

**Comment by amorey** [comment]
Thanks! I merged the changes into the master branch and published a new version (3.5.5). Here's a new version of the payload:
https://cdn.rawgit.com/muicss/loadjs/3.5.5/dist/loadjs.min.js

Let me know if you notice any other issues with LoadJS!
